### ISSUE TITLE
出现了一些问题，无法正常使用

### ISSUE THREAD

**Issue by x99iONE** [BelowZeroKelvin/MCDR-CarpetBotList#1]
[MCDR] [22:33:50] [PT3-on_info@CarpetBotList/ERROR]: Error calling on_info in plugin CarpetBotList
Traceback (most recent call last):
  File "F:\test\test\utils\plugin_thread.py", line 41, in run
    task_data.func(*task_data.args)
  File "plugins\CarpetBotList.py", line 66, in on_info
    server.say(msg_list_bot(server))
  File "plugins\CarpetBotList.py", line 52, in msg_list_bot
    .h(RText(' [' + worlds[bot[1][0]] + '§r] \n(' + ','.join([str(int(i)) for i in bot[1][1]]) + ') '))
TypeError: list indices must be integers or slices, not str

**Comment by BelowZeroKelvin** [comment]
已修复
